### ISSUE TITLE
Feat req: Notes on getting new grad FT

### ISSUE THREAD

**Issue by kaustavha** [evykassirer/playing-the-internship-game#32]
Heya,
Absolutely love this guide y'all have written.
I'd love some tips on getting a new grad FT, if theres any differences.
Also peoples thoughts on setting up the resume through undergrad to maximize success at that point.
I've also been using mattermark to find companies and understand their growth & potential. That might be a nice tool to mention as well.

**Comment by rudi-c** [comment]
Hi @kaustavha ! Thanks for the feedback. Although getting an internship and a new grad position is more similar than different, companies do see it a bit differently since the new grad will be staying around for much longer, therefore is a higher risk. The new grad will also get more responsibilities.

I haven't given deep thought to this subject yet, and I just started a full-time position myself. It might take another few months before I gather enough insights to write a section about. In the meantime, if anyone is reading this and has good insights/links to good articles, please share!

**Comment by evykassirer** [comment]
Thanks for recommending Mattermark! I added it in dac597de54e0f1a1423a02716d32edfbe7f75b5b

I have not graduated yet so I feel like I'm not qualified to answer about full time yet haha - but let us know if you figure anything out that would be good to add here!
